export type PaintingCategory = 'Landscape' | 'Abstract' | 'Portrait' | 'Nature' | 'Floral' | 'Animals' | 'Still Life' | 'Urban'

export interface Painting {
  id: string
  title: string
  description: string
  story: string
  price: number
  category: PaintingCategory
  medium: string
  dimensions: {
    width: number
    height: number
    unit: string
  }
  availability: 'Available' | 'Sold'
  image: string
  artist: string
  year: number
}

export const paintings: Painting[] = [
  {
    id: '1',
    title: 'Morning Bloom',
    description: 'A serene landscape capturing the first light of dawn over rolling hills.',
    story: 'This piece was inspired by a misty morning in the countryside. I watched as light gradually revealed layers of nature&apos;s beauty.',
    price: 850,
    category: 'Landscape',
    medium: 'Oil on Canvas',
    dimensions: { width: 24, height: 36, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1579783902614-e3fb5141b0cb?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '2',
    title: 'Celestial Dreams',
    description: 'An abstract exploration of colors and emotions through flowing brushstrokes.',
    story: 'Created during a moment of pure inspiration, this abstract piece represents the flow of emotions and the freedom of expression.',
    price: 720,
    category: 'Abstract',
    medium: 'Acrylic on Canvas',
    dimensions: { width: 30, height: 30, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1561214115-6f2f134cc4b1?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '3',
    title: 'Whispered Thoughts',
    description: 'A delicate portrait capturing a moment of quiet contemplation.',
    story: 'This portrait was inspired by the beauty of human emotion and the stories we hold within ourselves. Each brushstroke carries intention.',
    price: 950,
    category: 'Portrait',
    medium: 'Oil on Canvas',
    dimensions: { width: 20, height: 24, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1578926314433-e7eff60fcf40?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '4',
    title: 'Garden Sanctuary',
    description: 'A vibrant celebration of botanical beauty and natural harmony.',
    story: 'Inspired by my own garden in bloom, this piece captures the joy and energy of nature&apos;s most colorful moments.',
    price: 680,
    category: 'Floral',
    medium: 'Watercolor & Gouache',
    dimensions: { width: 18, height: 24, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1579783902614-e3fb5141b0cb?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '5',
    title: 'Mountain Silence',
    description: 'Majestic peaks wrapped in mystery and mist.',
    story: 'A tribute to the Alps, painted after a transformative journey through the mountains. Every peak tells a story of resilience.',
    price: 1100,
    category: 'Landscape',
    medium: 'Oil on Canvas',
    dimensions: { width: 36, height: 48, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1577720643272-265e434f0e23?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2023,
  },
  {
    id: '6',
    title: 'Untamed Spirit',
    description: 'A wild horse running free through an endless prairie.',
    story: 'This painting celebrates freedom and the untamed beauty of nature. It represents breaking free from constraints.',
    price: 890,
    category: 'Animals',
    medium: 'Acrylic on Canvas',
    dimensions: { width: 28, height: 36, unit: 'inches' },
    availability: 'Sold',
    image: 'https://images.unsplash.com/photo-1578906549254-62f0eb87ad75?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2023,
  },
  {
    id: '7',
    title: 'Quiet Moments',
    description: 'A still life study of everyday objects transformed through light and shadow.',
    story: 'Inspired by the beauty found in simplicity, this still life celebrates the ordinary made extraordinary.',
    price: 520,
    category: 'Still Life',
    medium: 'Oil on Canvas',
    dimensions: { width: 20, height: 20, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1578926314433-e7eff60fcf40?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '8',
    title: 'Urban Pulse',
    description: 'The energy and rhythm of city life captured in dynamic brushstrokes.',
    story: 'A love letter to urban landscapes, this piece captures the heartbeat of metropolitan life and human connection.',
    price: 760,
    category: 'Urban',
    medium: 'Mixed Media on Canvas',
    dimensions: { width: 24, height: 36, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1575934865162-7cb0622ab6fb?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '9',
    title: 'Botanical Dreams',
    description: 'Intricate details of flowering vines and nature&apos;s delicate intricacies.',
    story: 'This detailed study celebrates the patience required to observe nature. Each leaf and petal is rendered with intention.',
    price: 640,
    category: 'Nature',
    medium: 'Watercolor on Paper',
    dimensions: { width: 16, height: 20, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1579783902614-e3fb5141b0cb?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '10',
    title: 'Chromatic Fusion',
    description: 'Bold colors and geometric forms merge in harmonious abstraction.',
    story: 'An exploration of how different colors interact and communicate, creating new meanings through combination.',
    price: 680,
    category: 'Abstract',
    medium: 'Acrylic on Canvas',
    dimensions: { width: 28, height: 28, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1561214115-6f2f134cc4b1?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '11',
    title: 'Golden Hour',
    description: 'Sunset light transforms the landscape into liquid gold.',
    story: 'Painted en plein air during a magical sunset, this piece captures a fleeting moment of natural beauty.',
    price: 820,
    category: 'Landscape',
    medium: 'Oil on Canvas',
    dimensions: { width: 24, height: 32, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1577720643272-265e434f0e23?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '12',
    title: 'Blooming Serenity',
    description: 'Soft florals frame a peaceful garden pathway.',
    story: 'This floral composition represents growth, hope, and the cyclic beauty of nature&apos;s renewal.',
    price: 700,
    category: 'Floral',
    medium: 'Watercolor & Acrylic',
    dimensions: { width: 22, height: 28, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1579783902614-e3fb5141b0cb?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '13',
    title: 'Graceful Gaze',
    description: 'A sensitive portrayal of introspection and grace.',
    story: 'This portrait explores the depth of human character through careful observation of subtle expressions.',
    price: 920,
    category: 'Portrait',
    medium: 'Oil on Canvas',
    dimensions: { width: 20, height: 24, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1578906549254-62f0eb87ad75?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2023,
  },
  {
    id: '14',
    title: 'Wildlife Wonder',
    description: 'A lion in its natural habitat, captured with power and presence.',
    story: 'This study celebrates the majesty and strength of wildlife, advocating for conservation and respect for nature.',
    price: 980,
    category: 'Animals',
    medium: 'Mixed Media on Canvas',
    dimensions: { width: 30, height: 40, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1578906549254-62f0eb87ad75?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '15',
    title: 'Ethereal Layers',
    description: 'Translucent colors create depth and movement through layering.',
    story: 'An exploration of transparency and opacity, this abstract piece plays with perception and visual harmony.',
    price: 750,
    category: 'Abstract',
    medium: 'Acrylic on Canvas',
    dimensions: { width: 32, height: 32, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1561214115-6f2f134cc4b1?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '16',
    title: 'Coastal Reverie',
    description: 'Waves and sand merge under a contemplative sky.',
    story: 'Inspired by time spent by the sea, this landscape captures the healing power of coastal environments.',
    price: 880,
    category: 'Landscape',
    medium: 'Oil on Canvas',
    dimensions: { width: 28, height: 36, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1577720643272-265e434f0e23?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '17',
    title: 'Forest Soul',
    description: 'Ancient trees stand as silent guardians of nature&apos;s mysteries.',
    story: 'A meditation on the wisdom and timelessness of forests, painted as a tribute to their preservation.',
    price: 900,
    category: 'Nature',
    medium: 'Oil on Canvas',
    dimensions: { width: 24, height: 36, unit: 'inches' },
    availability: 'Sold',
    image: 'https://images.unsplash.com/photo-1576926314433-e7eff60fcf40?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2023,
  },
  {
    id: '18',
    title: 'Prismatic Light',
    description: 'Light refracted into a spectrum of pure color and energy.',
    story: 'This abstract study celebrates light itself as the primary subject, exploring how it transforms and illuminates.',
    price: 780,
    category: 'Abstract',
    medium: 'Acrylic on Canvas',
    dimensions: { width: 26, height: 26, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1561214115-6f2f134cc4b1?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '19',
    title: 'Urban Garden',
    description: 'Nature thrives in unexpected places within the city.',
    story: 'A celebration of urban ecology and the resilience of nature, showing how life finds a way everywhere.',
    price: 620,
    category: 'Urban',
    medium: 'Mixed Media on Canvas',
    dimensions: { width: 20, height: 28, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1575934865162-7cb0622ab6fb?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
  {
    id: '20',
    title: 'Silent Song',
    description: 'Soft, contemplative tones create an atmosphere of quiet beauty.',
    story: 'This portrait captures a moment of internal harmony and self-reflection, inviting viewers into personal introspection.',
    price: 860,
    category: 'Portrait',
    medium: 'Watercolor on Paper',
    dimensions: { width: 18, height: 22, unit: 'inches' },
    availability: 'Available',
    image: 'https://images.unsplash.com/photo-1578906549254-62f0eb87ad75?w=500&h=700&fit=crop',
    artist: 'Bloomin Paints',
    year: 2024,
  },
]
